version: 2.1
orbs:
  # https://github.com/cypress-io/circleci-orb
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run:
          name: Saves page on test failure
          start: npm start
          wait-on: 'http://localhost:3777'
          spec: 'cypress/integration/on-failure.js'
          no-workspace: true
          post-steps:
            # the "on-failure.js" spec should have failed
            # but it should store the full page with resources
            - store_artifacts:
                path: failed
