version: 2.1
orbs:
  # https://github.com/cypress-io/circleci-orb
  cypress: cypress-io/cypress@3
workflows:
  build:
    jobs:
      - cypress/run:
          name: Saves page on test failure
          start: npm start
          wait-on: 'http://localhost:3777'
          command: 'npm run fail:example'
          no-workspace: true
          # save the standard Cypress screenshots saved on failure
          store_artifacts: true
          post-steps:
            # the "on-failure.js" spec should have failed
            # but it should store the full page with resources
            - store_artifacts:
                path: cypress/failed
            # same with other "savePage" calls
            - store_artifacts:
                path: page
